### PR TITLE
coc, contributing.md and templates from gdgvit/template

### PR DESCRIPTION
**Pull request by searchformyusername**

### CODE REVIEW

**Review by oke-aditya — CHANGES_REQUESTED** [review]
Kindly cite py_fresh repo in readme as it was created from this. 
OR
Raise a PR to py_fresh that this was one of the projects from template. 

This is needed as folder structure and Ci actions are taken and commit history of git

**Comment by searchformyusername** [comment]
> Kindly cite py_fresh repo in readme as it was created from this. 
> OR
> Raise a PR to py_fresh that this was one of the projects from template. 
> 
> This is needed as folder structure and Ci actions are taken and commit history of git

@oke-aditya I have got ur point. And a citation will be made to the oke-aditya/py_fresh .

I have one last question, does oke-aditya/py_fresh repo mention that if this repo is used as project template then citation is mandatory?

**Comment by oke-aditya** [comment]
Not mandatory. But it's something that devs do. If you actually click on use template it directly shows it was generated from this

**Comment by oke-aditya** [comment]
Since this looks fork / mirror / clone push. It's nice to have it in readme. It just makes a point why others should use that template 😀

**Comment by searchformyusername** [comment]
@oke-aditya yes I agree, If we have used this from you then it should be cited. I will make the pr to oke-aditya/py_fresh shortly.

**Review by oke-aditya — APPROVED** [review]
LGTM!!

**Comment by searchformyusername** [comment]
@L04DB4L4NC3R 
@oke-aditya done https://github.com/oke-aditya/py_fresh/pull/20

**Comment by searchformyusername** [comment]
Since a citation is made, this pr is closed.

**Pull request closed without merging**
