### PR TITLE
Updated mkdocs settings

### PR DESCRIPTION
**Pull request by ramaneswaran**

### CODE REVIEW

**Comment by Geek-ubaid** [comment]
@ramaneswaran github action is failing, please review

**Comment by ramaneswaran** [comment]
@Geek-ubaid 
The unittests and pypi packaging are pending, so they will fail for now. 
I am planning on resolving them further down the line

**Comment by ramaneswaran** [comment]
I have removed some github actions for CI testing in windows and Mac, and pypi packaging.
Currently the CI for Ubuntu is enabled 
When the project is closer to release we can enable and resolve them

**Comment by Geek-ubaid** [comment]
> I have removed some github actions for CI testing in windows and Mac, and pypi packaging.
> Currently the CI for Ubuntu is enabled
> When the project is closer to release we can enable and resolve them

okay got it, everyhting looks fine, merging the PR

**Pull request merged**
